name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Minumum Supported Rust Version (MSRV) is 1.63.0.
        toolchain: [1.63.0, stable, beta, nightly]
    steps:
      - uses: actions/checkout@v3
      - name: Update Toolchain
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup component add --toolchain ${{ matrix.toolchain }} rustfmt
          rustup component add --toolchain ${{ matrix.toolchain }} clippy
          rustup update ${{ matrix.toolchain }}
      - name: Lint
        run: |
          cargo clippy --all-targets
      - name: Format
        run: |
          cargo fmt -- --check
      - name: Build
        run: |
          cargo build --verbose
      - name: Test
        run: |
          cargo test --verbose
