name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        # Minumum Supported Rust Version (MSRV) is 1.63.0.
        toolchain: [1.63.0, stable, beta, nightly]
        include:
          - toolchain: 1.63.0
            msrv: true
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Update Toolchain
        run: |
          rustup default ${{ matrix.toolchain }}
          rustup component add --toolchain ${{ matrix.toolchain }} rustfmt
          rustup component add --toolchain ${{ matrix.toolchain }} clippy
          rustup update ${{ matrix.toolchain }}
      - name: Pin dependencies
        if: matrix.msrv
        run: | 
          cargo update -p allocator-api2 --precise "0.2.9" --verbose
          cargo update -p tempfile --precise 3.3.0
          cargo update -p log --precise 0.4.18
          cargo update -p zstd-sys --precise "2.0.8+zstd.1.5.5"
      - name: Lint all targets
        run: cargo clippy --all-targets
      - name: Format
        run: cargo fmt -- --check
      - name: Build with defeault features
        run: cargo build --verbose
      - name: Check release build on Rust ${{ matrix.toolchain }}
        run: cargo check --release --verbose --color always
      - name: Unit test
        run: cargo test --verbose --lib
      - name: Doc test
        run: cargo test --verbose --doc
  signet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync signet
        run: cargo test --verbose test_signet_syncs
  bitcoind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Integration test
        run: cargo test -- --test-threads 1 --skip test_signet_syncs --nocapture
